version: "3"
services:
  mecab:
    #    entrypoint: ["sh", "-c", "sleep 2073600"]
    image: wgtdocker/mecab-0.996-alpine3.12:latest
    volumes:
      - mecab-libexec:/usr/local/libexec
      - mecab-backup:/root/mecab-backup
      - mecab-etc:/usr/local/etc
      - mecab-include:/usr/local/include
    links:
      - web

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web

  web:
    entrypoint: ["sh", "-c", "sleep 2073600"]
    build:
      context: ./web/
    ports:
      - "8080:8080"
    links:
      - redis
    volumes:
      - mecab-libexec:/usr/local/libexec
      - mecab-backup:/root/mecab-backup
      - mecab-etc:/usr/local/etc
      - mecab-include:/usr/local/include

  redis:
    image: redis

volumes:
  mecab-libexec:
  mecab-backup:
  mecab-etc:
  mecab-include:
